easy_admin:
    site_name: 'X-Adventure Administration'
    design:
            brand_color: '#70b32e'
            menu:
                - { label: 'Imports' }
                - { label: 'BO Import', route: 'admin_bo_upload' }
                - { label: 'Planning Import', route: 'admin_planning_upload' }
                - { label: 'Entities' }
                - Customer
                - CustomerAltered
                - Guide
                - Groep
                - Planning
                - Agency
                - Location
                - { label: 'Types' }
                - AllInType
                - InsuranceType
                - GroupType
                - LodgingType
                - ProgramType
                - TravelType
    entities:
        # List the entity class name you want to manage

        Customer:
          class: App\Entity\Customer
          form:
            fields:
              - { property: 'customerId'}
              - { property: 'fileId'}
              - { property: 'periodId'}
              - { property: 'bookerId'}
              - { property: 'booker'}
              - { property: 'lastName'}
              - { property: 'firstName'}
              - { property: 'email'}
              - { property: 'birthdate',
                  type: 'Symfony\Component\Form\Extension\Core\Type\BirthdayType' }
              - { property: 'gsm'}
              - { property: 'nationalRegisterNumber'}
              - { property: 'expireDate'}
              - { property: 'size'}
              - { property: 'sizeInfo'}
              - { property: 'nameShortage'}
              - { property: 'emergencyNumber'}
              - { property: 'licensePlate'}
              - { property: 'typePerson'}
              - { property: 'infoCustomer'}
              - { property: 'infoFile'}
              - { property: 'agency'}
              - { property: 'location'}
              - { property: 'startDay'}
              - { property: 'endDay'}
              - { property: 'programType'}
              - { property: 'lodgingType'}
              - { property: 'allInType'}
              - { property: 'insuranceType'}
              - { property: 'travelGoType'}
              - { property: 'travelGoDate'}
              - { property: 'travelBackType'}
              - { property: 'travelBackDate'}
              - { property: 'boardingPoint'}
              - { property: 'activityOption'}
              - { property: 'groupName'}
              - { property: 'groupPreference'}
              - { property: 'lodgingLayout'}
              - { property: 'groupLayout'}
              - { property: 'bookerPayed'}
              - { property: 'payerId'}
              - { property: 'isCamper'}
              - { property: 'checkedIn'}
              - { property: 'totalExclInsurance'}
              - { property: 'insuranceValue'}

        CustomerAltered:
          class: App\Entity\Customer
          form:
            fields:
              - { property: 'birthdate',
                  type: 'Symfony\Component\Form\Extension\Core\Type\BirthdayType' }

        Agency:
          class: App\Entity\Agency

        AllInType:
          class: App\Entity\AllInType

        InsuranceType:
          class: App\Entity\InsuranceType

        LodgingType:
          class: App\Entity\LodgingType

        ProgramType:
          class: App\Entity\ProgramType

        TravelType:
          class: App\Entity\TravelType

        Location:
          class: App\Entity\Location

        GroupType:
          class: App\Entity\GroupType

        Groep:
          class: App\Entity\Groep

        Guide:
          class: App\Entity\Guide

        Planning:
          class: App\Entity\Planning