easy_admin:
    site_name: 'X-Adventure Administration'
    design:
            brand_color: '#70b32e'
            menu:
                - { label: 'BO Import', route: 'test' }
                - Customer
                - Agency
                - Location
                - { label: 'Types' }
                - AllInType
                - InsuranceType
                - GroupType
                - LodgingType
                - ProgramType
                - TravelType
    entities:
        # List the entity class name you want to manage
        - App\Entity\Customer
        - App\Entity\Agency
        - App\Entity\AllInType
        - App\Entity\InsuranceType
        - App\Entity\LodgingType
        - App\Entity\ProgramType
        - App\Entity\TravelType
        - App\Entity\Location
        - App\Entity\GroupType