easy_admin:
    site_name: 'X-Adventure Administration'
    design:
            brand_color: '#70b32e'
            menu:
                - { label: 'Imports' }
                - { label: 'BO Import', route: 'admin_bo_upload' }
                - { label: 'Planning Import', route: 'admin_bo_upload' }
                - Customer
                - Agency
                - Location
                - { label: 'Types' }
                - AllInType
                - InsuranceType
                - GroupType
                - LodgingType
                - ProgramType
                - TravelType
    entities:
        # List the entity class name you want to manage

        Customer:
          class: App\Entity\Customer

        Agency:
          class: App\Entity\Agency

        AllInType:
          class: App\Entity\AllInType

        InsuranceType:
          class: App\Entity\InsuranceType

        LodgingType:
          class: App\Entity\LodgingType

        ProgramType:
          class: App\Entity\ProgramType

        TravelType:
          class: App\Entity\TravelType

        Location:
          class: App\Entity\Location

        GroupType:
          class: App\Entity\GroupType