easy_admin:
    site_name: 'X-Adventure Administration'
    design:
            brand_color: '#70b32e'
            menu:
                - { label: 'Imports' }
                - { label: 'Planning Import', route: 'admin_planning_upload' }
                - { label: 'BO Import', route: 'admin_bo_upload' }
                - { label: 'Forms' }
                - FormCheckin
                - FormSizes
                - FormGroupLayout
                - FormLodgingLayout
                - FormOptions
                - FormPayment
                - FormBill
                - { label: 'Entities' }
                - Customer
                - Guide
                - Groep
                - Planning
                - Agency
                - Location
                - Activity
                - Program
                - ProgramActivity
                - { label: 'Types' }
                - AllInType
                - InsuranceType
                - GroupType
                - LodgingType
                - ProgramType
                - TransportType
                - TravelType
                - SuitSize
                - HelmSize
                - BeltSize
                - ProgramGroup
                - ActivityGroup
    entities:
        # List the entity class name you want to manage

        Customer:
          class: App\Entity\Customer
          form:
            fields:
              - { property: 'customerId'}
              - { property: 'fileId'}
              - { property: 'periodId'}
              - { property: 'bookerId'}
              - { property: 'booker'}
              - { property: 'lastName'}
              - { property: 'firstName'}
              - { property: 'email'}
              - { property: 'birthdate',
                  type: 'Symfony\Component\Form\Extension\Core\Type\BirthdayType' }
              - { property: 'gsm'}
              - { property: 'nationalRegisterNumber'}
              - { property: 'expireDate'}
              - { property: 'size'}
              - { property: 'sizeInfo'}
              - { property: 'nameShortage'}
              - { property: 'emergencyNumber'}
              - { property: 'licensePlate'}
              - { property: 'typePerson'}
              - { property: 'infoCustomer'}
              - { property: 'infoFile'}
              - { property: 'agency'}
              - { property: 'location'}
              - { property: 'startDay'}
              - { property: 'endDay'}
              - { property: 'programType'}
              - { property: 'lodgingType'}
              - { property: 'allInType'}
              - { property: 'insuranceType'}
              - { property: 'travelGoType'}
              - { property: 'travelGoDate'}
              - { property: 'travelBackType'}
              - { property: 'travelBackDate'}
              - { property: 'boardingPoint'}
              - { property: 'activityOption'}
              - { property: 'groupName'}
              - { property: 'groupPreference'}
              - { property: 'lodgingLayout'}
              - { property: 'groupLayout'}
              - { property: 'bookerPayed'}
              - { property: 'payerId'}
              - { property: 'isCamper'}
              - { property: 'checkedIn'}
              - { property: 'totalExclInsurance'}
              - { property: 'insuranceValue'}
              - { property: 'activities'}

        FormSizes:
          class: App\Entity\Customer
          list:
            fields:
              - { property: 'groupLayout'}
              - { property: 'firstName'}
              - { property: 'lastName'}
              - { property: 'size'}
              - { property: 'sizeInfo'}
          form:
            fields:
              - { property: 'size'}
              - { property: 'sizeInfo'}

        FormCheckin:
            class: App\Entity\Customer
            list:
              fields:
                - { property: 'checkedIn'}
                - { property: 'firstName'}
                - { property: 'lastName'}
                - { property: 'booker'}
                - { property: 'groupName'}
                - { property: 'birthdate'}
                - { property: 'nationalRegisterNumber'}
                - { property: 'expireDate'}
                - { property: 'lodgingLayout'}
                - { property: 'allInType'}
                - { property: 'groupLayout'}
            form:
              fields:
                - { property: 'checkedIn'}
                - { property: 'firstName'}
                - { property: 'lastName'}
                - { property: 'booker'}
                - { property: 'groupName'}
                - { property: 'birthdate',
                    type: 'Symfony\Component\Form\Extension\Core\Type\BirthdayType' }
                - { property: 'nationalRegisterNumber'}
                - { property: 'expireDate'}
                - { property: 'lodgingLayout'}
                - { property: 'allInType'}
                - { property: 'groupLayout'}

        FormBill:
            class: App\Entity\Customer
            list:
              fields:
                - { property: 'groupLayout'}
                - { property: 'booker'}
                - { property: 'firstName'}
                - { property: 'lastName'}
                - { property: 'payments'}
                - { property: 'bookerPayed'}
            form:
              fields:
                - { property: 'payments'}
                - { property: 'bookerPayed'}

        FormGroupLayout:
            class: App\Entity\Customer
            list:
              fields:
                - { property: 'groupLayout'}
                - { property: 'groupPreference'}
                - { property: 'programType'}
                - { property: 'groupName'}
                - { property: 'booker'}
                - { property: 'travelGoType'}
                - { property: 'birthdate'}
                - { property: 'firstName'}
                - { property: 'lastName'}
            form:
              fields:
                - { property: 'groupLayout'}

        FormLodgingLayout:
            class: App\Entity\Customer
            list:
              fields:
                - { property: 'groupName'}
                - { property: 'booker'}
                - { property: 'firstName'}
                - { property: 'lastName'}
                - { property: 'lodgingType'}
                - { property: 'lodgingLayout'}

            form:
              fields:
                - { property: 'lodgingLayout'}

        FormOptions:
            class: App\Entity\Customer
            list:
              fields:
                - { property: 'groupLayout'}
                - { property: 'programType'}
                - { property: 'firstName'}
                - { property: 'lastName'}
                - { property: 'activities'}
            form:
              fields:
                - { property: 'activities'}

        Agency:
          class: App\Entity\Agency
          list:
            fields:
              - { property: 'id'}
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'agencyCustomers'}
          form:
            fields:
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'agencyCustomers', type_options: { by_reference: false }}

        AllInType:
          class: App\Entity\AllInType
          list:
            fields:
              - { property: 'id'}
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'price'}
              - { property: 'allCustomers'}
          form:
            fields:
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'price'}
              - { property: 'allCustomers', type_options: { by_reference: false }}

        InsuranceType:
          class: App\Entity\InsuranceType
          list:
            fields:
              - { property: 'id'}
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'insuranceCode'}
              - { property: 'insuranceName'}
              - { property: 'insCustomers'}
          form:
            fields:
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'insuranceCode'}
              - { property: 'insuranceName'}
              - { property: 'insCustomers', type_options: { by_reference: false }}

        LodgingType:
          class: App\Entity\LodgingType
          list:
            fields:
              - { property: 'id'}
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'lodgingCustomers'}
          form:
            fields:
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'lodgingCustomers', type_options: { by_reference: false }}

        ProgramType:
          class: App\Entity\ProgramType
          list:
            fields:
              - { property: 'id'}
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'programCustomers'}
          form:
            fields:
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'programCustomers', type_options: { by_reference: false }}

        TravelType:
          class: App\Entity\TravelType

        TransportType:
          class: App\Entity\TransportType
          list:
            fields:
              - { property: 'id'}
              - { property: 'name'}
              - { property: 'travelTypes'}
          form:
            fields:
              - { property: 'name'}
              - { property: 'travelTypes', type_options: { by_reference: false }}

        Location:
          class: App\Entity\Location
          list:
            fields:
              - { property: 'id'}
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'locCustomers'}
          form:
            fields:
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'locCustomers', type_options: { by_reference: false }}

        GroupType:
          class: App\Entity\GroupType
          list:
            fields:
              - { property: 'id'}
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'agency'}
              - { property: 'customers'}
          form:
            fields:
              - { property: 'code'}
              - { property: 'description'}
              - { property: 'agency'}
              - { property: 'customers', type_options: { by_reference: false }}

        Groep:
          class: App\Entity\Groep
          list:
            fields:
              - { property: 'id'}
              - { property: 'groupId'}
              - { property: 'periodId'}
              - { property: 'name'}
              - { property: 'location'}
              - { property: 'groupPlannings'}
              - { property: 'groupCustomers'}
          form:
            fields:
              - { property: 'groupId'}
              - { property: 'periodId'}
              - { property: 'name'}
              - { property: 'location'}
              - { property: 'groupPlannings', type_options: { by_reference: false }}
              - { property: 'groupCustomers', type_options: { by_reference: false }}

        Guide:
          class: App\Entity\Guide
          list:
            fields:
              - { property: 'id'}
              - { property: 'guideShort'}
              - { property: 'guideFirstName'}
              - { property: 'guideLastName'}
              - { property: 'plannings'}
          form:
            fields:
              - { property: 'guideShort'}
              - { property: 'guideFirstName'}
              - { property: 'guideLastName'}
              - { property: 'plannings', type_options: { by_reference: false }}

        SuitSize:
          class: App\Entity\SuitSize
          list:
            fields:
              - { property: 'id'}
              - { property: 'sizeId'}
              - { property: 'name'}
              - { property: 'beltSize'}
              - { property: 'helmSize'}
              - { property: 'suitCustomers'}
          form:
            fields:
              - { property: 'sizeId'}
              - { property: 'name'}
              - { property: 'beltSize'}
              - { property: 'helmSize'}
              - { property: 'suitCustomers', type_options: { by_reference: false }}

        HelmSize:
          class: App\Entity\HelmSize
          list:
            fields:
              - { property: 'id'}
              - { property: 'name'}
              - { property: 'helmSuitSizes'}
          form:
            fields:
              - { property: 'name'}
              - { property: 'helmSuitSizes', type_options: { by_reference: false }}

        BeltSize:
          class: App\Entity\BeltSize
          list:
            fields:
              - { property: 'id'}
              - { property: 'name'}
              - { property: 'beltSuitSizes'}
          form:
            fields:
              - { property: 'name'}
              - { property: 'beltSuitSizes', type_options: { by_reference: false }}

        Planning:
          class: App\Entity\Planning
          list:
            fields:
              - { property: 'id'}
              - { property: 'planningId'}
              - { property: 'date'}
              - { property: 'group'}
              - { property: 'activity'}
              - { property: 'guide'}
              - { property: 'guideFunction'}
          form:
            fields:
              - { property: 'id'}
              - { property: 'planningId'}
              - { property: 'date'}
              - { property: 'group', type_options: { by_reference: false }}
              - { property: 'activity', type_options: { by_reference: false }}
              - { property: 'guide', type_options: { by_reference: false }}
              - { property: 'guideFunction'}

        ActivityGroup:
          class: App\Entity\ActivityGroup
          list:
            fields:
              - { property: 'id'}
              - { property: 'name'}
              - { property: 'activities'}
          form:
            fields:
              - { property: 'name'}
              - { property: 'activities', type_options: { by_reference: false }}

        ProgramGroup:
          class: App\Entity\ProgramGroup
          list:
            fields:
              - { property: 'id'}
              - { property: 'name'}
              - { property: 'programs'}
          form:
            fields:
              - { property: 'name'}
              - { property: 'programs', type_options: { by_reference: false }}

        Activity:
          class: App\Entity\Activity
          list:
            fields:
              - { property: 'id'}
              - { property: 'name'}
              - { property: 'programActivities'}
              - { property: 'agency'}
              - { property: 'activityGroup'}
              - { property: 'activityPlannings'}
              - { property: 'price'}
              - { property: 'customers'}
              - { property: 'location'}
          form:
            fields:
              - { property: 'name'}
              - { property: 'programActivities', type_options: { by_reference: false }}
              - { property: 'activityPlannings', type_options: { by_reference: false }}
              - { property: 'agency'}
              - { property: 'activityGroup'}
              - { property: 'price'}
              - { property: 'customers', type_options: { by_reference: false }}
              - { property: 'location'}

        Program:
          class: App\Entity\Program
          list:
            fields:
              - { property: 'id'}
              - { property: 'name'}
              - { property: 'activityPrograms'}
              - { property: 'agency'}
              - { property: 'programGroup'}
              - { property: 'days'}
              - { property: 'programType'}
              - { property: 'location'}
          form:
            fields:
              - { property: 'name'}
              - { property: 'activityPrograms', type_options: { by_reference: false }}
              - { property: 'agency'}
              - { property: 'programGroup'}
              - { property: 'days'}
              - { property: 'programType'}
              - { property: 'location'}

        ProgramActivity:
          class: App\Entity\ProgramActivity

        FormPayment:
          class: App\Entity\Payment
          list:
            fields:
              - { property: 'customer'}
              - { property: 'description'}
              - { property: 'price'}
          form:
            fields:
              - { property: 'customer'}
              - { property: 'description'}
              - { property: 'price'}