easy_admin:
    site_name: 'X-Adventure Administration'
    design:
            brand_color: '#70b32e'
            menu:
                - { label: 'Imports' }
                - { label: 'BO Import', route: 'admin_bo_upload' }
                - { label: 'Planning Import', route: 'admin_planning_upload' }
                - { label: 'Forms' }
                - FormCheckin
                - FormSizes
                - FormGroupLayout
                - FormLodgingLayout
                - { label: 'Entities' }
                - Customer
                - Guide
                - Groep
                - Planning
                - Agency
                - Location
                - Activity
                - { label: 'Types' }
                - AllInType
                - InsuranceType
                - GroupType
                - LodgingType
                - ProgramType
                - TransportType
                - TravelType
                - SuitSize
                - HelmSize
                - BeltSize
                - ProgramGroup
                - ActivityGroup
    entities:
        # List the entity class name you want to manage

        Customer:
          class: App\Entity\Customer
          form:
            fields:
              - { property: 'customerId'}
              - { property: 'fileId'}
              - { property: 'periodId'}
              - { property: 'bookerId'}
              - { property: 'booker'}
              - { property: 'lastName'}
              - { property: 'firstName'}
              - { property: 'email'}
              - { property: 'birthdate',
                  type: 'Symfony\Component\Form\Extension\Core\Type\BirthdayType' }
              - { property: 'gsm'}
              - { property: 'nationalRegisterNumber'}
              - { property: 'expireDate'}
              - { property: 'size'}
              - { property: 'sizeInfo'}
              - { property: 'nameShortage'}
              - { property: 'emergencyNumber'}
              - { property: 'licensePlate'}
              - { property: 'typePerson'}
              - { property: 'infoCustomer'}
              - { property: 'infoFile'}
              - { property: 'agency'}
              - { property: 'location'}
              - { property: 'startDay'}
              - { property: 'endDay'}
              - { property: 'programType'}
              - { property: 'lodgingType'}
              - { property: 'allInType'}
              - { property: 'insuranceType'}
              - { property: 'travelGoType'}
              - { property: 'travelGoDate'}
              - { property: 'travelBackType'}
              - { property: 'travelBackDate'}
              - { property: 'boardingPoint'}
              - { property: 'activityOption'}
              - { property: 'groupName'}
              - { property: 'groupPreference'}
              - { property: 'lodgingLayout'}
              - { property: 'groupLayout'}
              - { property: 'bookerPayed'}
              - { property: 'payerId'}
              - { property: 'isCamper'}
              - { property: 'checkedIn'}
              - { property: 'totalExclInsurance'}
              - { property: 'insuranceValue'}

        FormSizes:
          class: App\Entity\Customer
          list:
            fields:
              - { property: 'groupLayout'}
              - { property: 'firstName'}
              - { property: 'lastName'}
              - { property: 'size'}
              - { property: 'sizeInfo'}
          form:
            fields:
              - { property: 'size'}
              - { property: 'sizeInfo'}

        FormCheckin:
            class: App\Entity\Customer
            list:
              fields:
                - { property: 'checkedIn'}
                - { property: 'firstName'}
                - { property: 'lastName'}
                - { property: 'booker'}
                - { property: 'groupName'}
                - { property: 'birthdate'}
                - { property: 'nationalRegisterNumber'}
                - { property: 'expireDate'}
                - { property: 'lodgingLayout'}
                - { property: 'allInType'}
                - { property: 'groupLayout'}
            form:
              fields:
                - { property: 'checkedIn'}
                - { property: 'firstName'}
                - { property: 'lastName'}
                - { property: 'booker'}
                - { property: 'groupName'}
                - { property: 'birthdate',
                    type: 'Symfony\Component\Form\Extension\Core\Type\BirthdayType' }
                - { property: 'nationalRegisterNumber'}
                - { property: 'expireDate'}
                - { property: 'lodgingLayout'}
                - { property: 'allInType'}
                - { property: 'groupLayout'}

        FormGroupLayout:
            class: App\Entity\Customer
            list:
              fields:
                - { property: 'groupLayout'}
                - { property: 'groupPreference'}
                - { property: 'programType'}
                - { property: 'groupName'}
                - { property: 'booker'}
                - { property: 'travelGoType'}
                - { property: 'birthdate'}
                - { property: 'firstName'}
                - { property: 'lastName'}
            form:
              fields:
                - { property: 'groupLayout'}

        FormLodgingLayout:
            class: App\Entity\Customer
            list:
              fields:
                - { property: 'groupName'}
                - { property: 'booker'}
                - { property: 'firstName'}
                - { property: 'lastName'}
                - { property: 'lodgingType'}
                - { property: 'lodgingLayout'}

            form:
              fields:
                - { property: 'lodgingLayout'}

        Agency:
          class: App\Entity\Agency

        AllInType:
          class: App\Entity\AllInType

        InsuranceType:
          class: App\Entity\InsuranceType

        LodgingType:
          class: App\Entity\LodgingType

        ProgramType:
          class: App\Entity\ProgramType

        TravelType:
          class: App\Entity\TravelType

        TransportType:
          class: App\Entity\TransportType

        Location:
          class: App\Entity\Location

        GroupType:
          class: App\Entity\GroupType

        Groep:
          class: App\Entity\Groep

        Guide:
          class: App\Entity\Guide

        SuitSize:
          class: App\Entity\SuitSize

        HelmSize:
          class: App\Entity\HelmSize

        BeltSize:
          class: App\Entity\BeltSize

        Planning:
          class: App\Entity\Planning

        ActivityGroup:
          class: App\Entity\ActivityGroup

        ProgramGroup:
          class: App\Entity\ProgramGroup

        Activity:
          class: App\Entity\Activity