fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    registration:
        confirmation:
            enabled: true
            from_email:
                address: "%mailer_user%"
                sender_name: X-Adventure
    from_email:
        address: "%mailer_user%"
        sender_name: X-Adventure
    resetting:
        email:
            from_email:
                address: "%mailer_user%"
                sender_name: X-Adventure