# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:

  view:
      view_response_listener:  true
#  exception:
#      codes:
#          App\Exception\MyException: 403
#      messages:
#          App\Exception\MyException: Forbidden area.
  format_listener:
    enabled: true
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      -
        path: '^/'
        stop: true
  serializer:
      serialize_null: true